### ISSUE TITLE
UnboundLocalError: local variable 'res_le' referenced before assignment

### ISSUE THREAD

**Issue by AtalsZem** [AlessandroRuzzi/GazeNeRF#4]
When I run dataset_pre_processing.py, the following error occurs:

Traceback (most recent call last):
  File "/data/workspace/diffusion/GazeNeRF/dataset_pre_processing.py", line 539, in <module>
    dataset_processing(
  File "/data/workspace/diffusion/GazeNeRF/dataset_pre_processing.py", line 474, in dataset_processing
    eth_xgaze_dataset_iteration_full(
  File "/data/workspace/diffusion/GazeNeRF/dataset_pre_processing.py", line 218, in eth_xgaze_dataset_iteration_full
    ) = main_process(
  File "/data/workspace/diffusion/GazeNeRF/pre_processing/data_process.py", line 46, in main_process
    head_masks, left_eye_masks, right_eye_masks = tt.main_process(img_dir=img_dir)
  File "/data/workspace/diffusion/GazeNeRF/pre_processing/gen_all_masks.py", line 237, in main_process
    res_re[:, : int(res_le.shape[1] / 2)] = 0
UnboundLocalError: local variable 'res_le' referenced before assignment

**Comment by AtalsZem** [comment]
Thers are two mistakes in file pre_processing/gen_all_masks.py at [line 237](https://github.com/AlessandroRuzzi/GazeNeRF/blob/f00e60ffa40255c6c4240f8bc2a20d800d9a4a1d/pre_processing/gen_all_masks.py#L237) and [line 256](https://github.com/AlessandroRuzzi/GazeNeRF/blob/f00e60ffa40255c6c4240f8bc2a20d800d9a4a1d/pre_processing/gen_all_masks.py#L256), res_le should be res_re.

**Comment by X-Shi** [comment]
Thank you for pointing them out. They are indeed typos. I will modify them.
